version: '3.8'
services:
  app:
    build: .
    volumes: 
      - .:/app
    ports:
       - 8000:8000
    image: app:goin_backend
    container_name: goin_backend_container
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - /Library/PostgreSQL/15/data:/data
    environment:
      - POSGTRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db



