version: '3.8'
services:
  app:
    build: .
    volumes: 
      - .:/app
    ports:
       - 8000:8000
    image: app:goin_backend
    container_name: goin_backend_container
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres_db
    networks:
      - goinnetwork

  postgres_db:
    image: postgres:15
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
       - 5432:5432
    environment:
      - POSGTRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: postgres_db
    networks:
      - goinnetwork
      
networks:
  goinnetwork:
    driver: bridge