# Generated by Django 4.1.3 on 2022-12-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Locations",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=256)),
                ("desc", models.TextField(verbose_name="Description")),
                ("url", models.CharField(max_length=1024)),
                ("address", models.CharField(max_length=1024)),
                ("image_url", models.CharField(max_length=1024)),
            ],
        ),
    ]
