# Generated by Django 4.1.5 on 2023-01-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goin_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bands",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=512)),
                ("desc", models.TextField(null=True)),
                ("url", models.CharField(max_length=1024, null=True)),
                ("image_url", models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GenreTags",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=512)),
                ("desc", models.TextField(null=True)),
                ("url", models.CharField(max_length=1024, null=True)),
                ("image_url", models.CharField(max_length=1024, null=True)),
                ("ticket_url", models.CharField(max_length=1024, null=True)),
                ("finish_datetime", models.DateTimeField(null=True)),
                (
                    "band_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goin_backend.bands",
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goin_backend.locations",
                    ),
                ),
            ],
        ),
    ]
