# Generated by Django 4.1.5 on 2023-01-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goin_backend", "0002_bands_genretags_events"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bands",
            new_name="Band",
        ),
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
        migrations.RenameModel(
            old_name="GenreTags",
            new_name="GenreTag",
        ),
        migrations.RenameModel(
            old_name="Locations",
            new_name="Location",
        ),
    ]
