# Generated by Django 4.1.5 on 2023-01-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goin_backend', '0003_rename_bands_band_rename_events_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genretag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
